# Be sure to restart your server when you modify this file.
# Your secret key is used for verifying the integrity of signed cookies.

development:
  secret_key_base: THIS_TOKEN_WILL_BE_REWRITED_WITH_DEPLOYMENT_TOOL_DONT_WORRY_ABOUT_IT_ON_PRODUCTION

test:
  secret_key_base: THIS_TOKEN_WILL_BE_REWRITED_WITH_DEPLOYMENT_TOOL_DONT_WORRY_ABOUT_IT_ON_PRODUCTION
